version: "3.3"
services:
  app-redis:
    container_name: "app-redis"
    image: 'redis:alpine'

  data-parser:
    build:
      context: ./
    ports:
      - "9000:9000"
    volumes:
      - ./:/data-parser/
